### ISSUE TITLE
小米手机上测试java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication

### ISSUE THREAD

**Issue by zhourihu5** [gumingwei/WellSwipe#1]
java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to com.well.swipe.SwipeApplication
08-17 09:59:40.571 10877-10877/com.well.swipe W/System.err:     at com.well.swipe.SwipeProvider.onCreate(SwipeProvider.java:81)
08-17 09:59:40.571 10877-10877/com.well.swipe W/System.err:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1754)
08-17 09:59:40.571 10877-10877/com.well.swipe W/System.err:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1729)
08-17 09:59:40.571 10877-10877/com.well.swipe W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:5189)
08-17 09:59:40.571 10877-10877/com.well.swipe W/System.err:     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4784)
08-17 09:59:40.571 10877-10877/com.well.swipe W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4724)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:153)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5459)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
08-17 09:59:40.572 10877-10877/com.well.swipe W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by gumingwei** [comment]
@zhourihu5  看到了，我排查一下

**Comment by LinXiaoTao** [comment]
这个错误,我也遇到了.解决方法如下:
![2016-08-20 12 27 19](https://cloud.githubusercontent.com/assets/19836925/17828992/dbef1554-66d1-11e6-8ccd-2856a320f5a5.png)
需要关闭_即时运行_,具体原因还需要排查.

**Comment by LinXiaoTao** [comment]
还有需要升级下`gradle`版本,貌似低版本bug挺多的

```
classpath 'com.android.tools.build:gradle:2.1.3'
```

可以参考[stackoverflow](http://stackoverflow.com/questions/33967703/unable-to-instantiate-application-com-android-tools-fd-runtime-bootstrapapplicat)回答

**Comment by winston1991** [comment]
这个问题很变态，所有的高版本gradle全部试了还是闪退

**Comment by winston1991** [comment]
@gumingwei 有没有解决此BUG

**Comment by gumingwei** [comment]
@winston1991  这奇怪了啊

**Comment by pinocchio2mx** [comment]
我在红米2 MIUI8 上用2.2.2的gradle插件会报这个错，用2.2.0就没问题

**Comment by gumingwei** [comment]
@pinocchio2mx 解决了，可以把解决方式贴上来

**Comment by pinocchio2mx** [comment]
@gumingwei 我就是把classpath 'com.android.tools.build:gradle:2.2.2'改成classpath 'com.android.tools.build:gradle:2.2.0'了呀
